title: Minimal theme
logo: /assets/img/pngtree-banyan-tree-logo-design-vector-png-image_6131481.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
